![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [3]:
# your code goes here
A = np.array([0]*10)
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [6]:
# your code goes here
B=np.arange(10,50)
B

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [7]:
# your code goes here
C=np.array([
            [1,1],
            [1,1]])
C.shape

(2, 2)

In [8]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [11]:
# your code goes here
D = np.ones([3,2], dtype=np.float)
D

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [15]:
# your code goes here
E = np.ones([4], dtype = np.int)
E

array([1, 1, 1, 1])

In [13]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [20]:
# your code goes here
X1 = np.zeros([2,3], dtype=np.int)
X1

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [25]:
# your code goes here
F = np.ones([4,4], dtype=np.int)
F = F*5
F

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [26]:
np.ones([4,4], dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [27]:
# your code goes here
X = np.array([[2,3], [6,2]], dtype=np.int)
np.ones_like(X)*7

array([[7, 7],
       [7, 7]])

In [28]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [31]:
# your code goes here
G = np.identity(3)
G

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [57]:
H1 = np.random.randint(3,20,3)
H1

array([19, 10, 13])

In [44]:
# your code goes here
H = np.random.randint(10, size=3)
H


array([5, 2, 0])

In [45]:
np.random.randint(10, size=3)

array([3, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [51]:
# your code goes here
I = np.random.randn(3, 3, 3)
I

array([[[-1.20756784, -0.12735848,  0.70931342],
        [-2.87692564, -0.61370657, -0.90140197],
        [-1.01172055,  0.48677083, -0.032227  ]],

       [[ 0.70185817, -0.32052589,  1.40920331],
        [ 0.75484003,  1.24230886, -0.68893252],
        [-1.21709473, -0.66470126, -0.06841253]],

       [[ 0.56056957,  0.17387445, -1.12352619],
        [ 0.56910224,  0.03012304, -0.21094977],
        [-0.31987736, -0.70873169,  0.2422048 ]]])

In [52]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 2.18154365,  1.14515738,  0.76939442],
        [ 1.53161112,  2.77542855,  0.72871557],
        [-0.2577065 , -0.41207559, -0.0863836 ]],

       [[ 0.51737905, -0.32342326, -0.64357426],
        [ 0.43596687,  0.63249358, -2.06790465],
        [-1.35420041, -0.28402273, -1.04750286]],

       [[-0.74255207, -0.70581649, -0.7203997 ],
        [-0.87704486,  0.48572415,  0.28684762],
        [-0.38319901, -1.37992188,  1.04166211]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [60]:
# your code goes here
X = [1, 2, 3]
print(X, type(X))

Y =np.array(X) 

print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [61]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [62]:
# your code goes here
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 140062212109776
[5 2 3] 140062212110736


In [63]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 140062211631984
[5 2 3] 140062207610272


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [68]:
# your code goes here
B2 = np.arange(1, 11)
B2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [71]:
# your code goes here
B3 = np.arange(1, 11, 2)
B3

array([1, 3, 5, 7, 9])

In [72]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [79]:
# your code goes here
B4 = np.arange(1, 11)[::-1]
B4

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [80]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [83]:
# your code goes here
D2 = np.arange(9).reshape(3,3)
D2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [ ]:
# your code goes here


In [85]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [86]:
# your code goes here
X = np.array(['A','B','C','D','E'])
X[0]

'A'

In [87]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [88]:
# your code goes here
X = np.array(['A','B','C','D','E'])
X[-1]

'E'

In [89]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [90]:
# your code goes here
X = np.array(['A','B','C','D','E'])
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [91]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [93]:
# your code goes here
X = np.array(['A','B','C','D','E'])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [94]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [95]:
# your code goes here
X = np.array(['A','B','C','D','E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [96]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [97]:
# your code goes here
X = np.array(['A','B','C','D','E'])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [98]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [99]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [100]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

In [101]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [102]:
# your code goes here
X[0,0]

1

In [103]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [104]:
# your code goes here
X[-1, -1]

16

In [105]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [107]:
# your code goes here
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [108]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [109]:
# your code goes here
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [110]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [112]:
# your code goes here
X[-2: , -2:]

array([[11, 12],
       [15, 16]])

In [113]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [117]:
# your code goes here
X = [-5, -3, 0, 10, 40]
X = np.array(X, dtype=float)
X

array([-5., -3.,  0., 10., 40.])

In [118]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [119]:
# your code goes here
X = [-5, -3, 0, 10, 40]
np.array(X)[::-1]

array([40, 10,  0, -3, -5])

In [120]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [122]:
# your code goes here
X = [0, 10, -5, 40, -3]
X.sort()

X

[-5, -3, 0, 10, 40]

In [123]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [124]:
# your code goes here
X = np.zeros(10)

X[4] = 1

X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [125]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [128]:
# your code goes here
X = np.array([10, 20, 30, 50])
X[3] = 40
X

array([10, 20, 30, 40])

In [129]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [132]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[3]=1

X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [133]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [134]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1]=0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [135]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [143]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X+5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [141]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [146]:
# your code goes here
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X<= 0

mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [144]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [148]:
# your code goes here
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask =X <= 0

X[mask]

array([-1,  0, -4,  0,  0, -9])

In [145]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [149]:
# your code goes here
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X >5

X[mask]

array([ 6, 10])

In [150]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [151]:
# your code goes here
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > X.mean()

X[mask]

array([ 2,  5,  6, 10])

In [152]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [160]:
# your code goes here
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = (X == 2) | (X==10)

X[mask]

array([ 2, 10])

In [159]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [164]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

In [165]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [166]:
# your code goes here
X.any()

True

In [167]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [168]:
# your code goes here
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

X.sum()

43

In [169]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [170]:
# your code goes here
X.mean()

4.777777777777778

In [171]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [172]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)

array([28, 32, 36, 40])

In [173]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [174]:
# your code goes here
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [175]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [176]:
# your code goes here
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

X.max()

10

In [177]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)