# Adjusted R-squared - Exercise

Using the code from the lecture, create a function which will calculate the adjusted R-squared for you, given the independent variable(s) (x) and the dependent variable (y).

Check if you function is working properly.

Please solve the exercise at the bottom of the notebook (in order to check if it is working you must run all previous cells).

## Import the relevant libraries

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
root_path = 'drive/My Drive/Colab Notebooks/'

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the data

In [10]:
data = pd.read_csv(root_path + '1.02._Multiple_linear_regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [11]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

## Create the multiple linear regression

### Declare the dependent and independent variables

In [12]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

### Regression itself

In [13]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [14]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [15]:
reg.intercept_

0.29603261264909486

### Calculating the R-squared

In [16]:
reg.score(x,y)

0.4066811952814283

### Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [17]:
x.shape

(84, 2)

In [18]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

### Adjusted R^2 function

In [20]:
def adj_r2(x, y):
    r2= reg.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adj_r2 = 1 - (1-r2)*(n-1)/(n-p-1)
    return adj_r2


In [21]:
adj_r2(x, y)

0.3920313482513401

In [22]:
from sklearn.feature_selection import f_regression

f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [23]:
p_value = f_regression(x,y)[1]

In [24]:
p_value

array([7.19951844e-11, 6.76291372e-01])

In [25]:
p_value.round(3)

array([0.   , 0.676])